

language: php

php:
    - 5.5
    - 5.6
    - 7.0

services:
    - postgresql
    - mysql

before_script:
    - createdb -Upostgres -EUTF-8 -Ttemplate0 zapstore_test_db
    - mysql -e 'CREATE DATABASE zapstore_test_db'
    - composer install -n -o --prefer-dist

script:
    - php ./vendor/bin/phpunit -c phpunit.xml

