
language: php

php:
    - 7.0
    - 7.4

services:
    - postgresql
    - mysql

before_install:
    - echo "extension=redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
    - redis-server --daemonize yes --requirepass 'xoxo'
    - createdb -Upostgres -EUTF-8 -Ttemplate0 zapstore_test_db
    - mysql -e 'CREATE DATABASE zapstore_test_db'
    - composer install -no

script:
    - php ./vendor/bin/phpunit

after_success:
    - curl -s https://codecov.io/bash | bash

notifications:
    email:
        on_success: never
        on_failure: always

