
language: php

php:
    - 5.5
    - 5.6
    - 7.1

services:
    - postgresql
    - mysql
    - redis-server

before_install:
    - echo "extension=redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
    - createdb -Upostgres -EUTF-8 -Ttemplate0 zapstore_test_db
    - mysql -e 'CREATE DATABASE zapstore_test_db'
    - composer install -no --prefer-dist

script:
    - php ./vendor/bin/phpunit

after_success:
    - curl -s https://codecov.io/bash | bash

notifications:
    email:
        on_success: never
        on_failure: always

